### ISSUE TITLE
Add environment variables

### ISSUE THREAD

**Issue by wilcorrea** [webdevops/Dockerfile#228]
Hey guys, first all congrats for job!! I did something like what is above here to use the image `webdevops/php-apache-dev:7.0`. How can I transform this in environment variables and PR it to project?
(with this changes I can just run `dc exec app composer install` without worries)

```
FROM webdevops/php-apache-dev:7.0

# Define the running user
USER application

# Application directory
WORKDIR "/var/www/app"
```

**Comment by wilcorrea** [comment]
Hi @PanadeEdu thanks for response. I wanna know how we can inform the `USER` and `WORKDIR` using environment section in **docker-compose** or -e using just **docker**.

**Comment by PanadeEdu** [comment]
Well as a first implementation, you can always add that to the provisioning however you want. As you already said by adding an docker-compose variable or by inheriting a new dockerfile on ours. 

I assume that you want this in the project since they are usefull environment variables.
We construct the Dockerfiles by inheritance from previous ones and by applying some substituting jinja templates.
We need tontaie a look if we have similar variables already and, if not, look of it makes sense to add it without bloating the images. 

Because Docker gives you a lot of freedom when it comes to building on top of images, we tend to keep them as general as possible.

**Comment by hhoechtl** [comment]
We already have ENV variables for that.

Those might be interesting for you:
```
WEB_DOCUMENT_ROOT=/app
APPLICATION_PATH=/app
CONTAINER_UID=application
APPLICATION_USER=application
APPLICATION_GROUP=application
APPLICATION_UID=1000
APPLICATION_GID=1000
```

**Comment by wilcorrea** [comment]
Thank you guys! Do you know where I can found about this on docs?

**Comment by hhoechtl** [comment]
It's not explained in detail (required some love), but http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/nginx.html is always a good entrypoint.
