### ISSUE TITLE
PHP 7.3.14 support

### ISSUE THREAD

**Issue by mrfroasty** [webdevops/Dockerfile#337]
Support for php 7.3.14, currently 7.3.11

**Comment by hhoechtl** [comment]
We already do:

```
➜  ~ docker pull webdevops/php:7.3
7.3: Pulling from webdevops/php
...
➜  ~ docker run --rm -ti webdevops/php:7.3 php -v
PHP 7.3.14 (cli) (built: Jan 24 2020 08:01:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.3.14, Copyright (c) 1999-2018, by Zend Technologies
```

Please always specify the image tag you are referring to, e.g. `webdevops/php-nginx:7.3`, otherwise we have many possible images referring to 7.3.

The images are rebuilt every night with the current version provided by the maintainers e.g. `php:7.3-fpm` or `ubuntu:18.04` etc.

You can see the builds at https://gitlab.com/webdevops/autobuild/pipelines or in our slack in the channel development.

**Comment by mrfroasty** [comment]
Thanks it works now, I was using `webdevops/php-nginx-dev:7.3`

**Comment by hhoechtl** [comment]
Be sure to always pull the newest image before you build ;-).
