### ISSUE TITLE
Do alpine tags needs updating?

### ISSUE THREAD

**Issue by coreyworrell** [webdevops/Dockerfile#355]
Shouldn't `webdevops/php-apache-dev:alpine` and `webdevops/php-apache-dev:alpine-php7` be updated to point to `7.4-alpine`? Currently they are still using 7.2.13

Thank you.

**Comment by hhoechtl** [comment]
No, they are totally different and not related.

**Comment by coreyworrell** [comment]
@hhoechtl what is the difference? Which one should I use to always have the latest php alpine version?

**Comment by hhoechtl** [comment]
The old `webdevops/php-apache-dev:alpine` and `webdevops/php-apache-dev:alpine-php7` images where based on `alpine` with the default PHP installation from the sources. They were locked to the alpine version.

The new images `:7.3-alpine` etc. are based on `php:fpm-alpine` which contains a fresh compiled PHP from the official releases and we just add our layers on top. The underlying alpine version may change.

There's currently no `latest` mechanism for the official PHP images, because you should never blindly switch PHP versions if we would e.g. release `:7.5-alpine` a pull on `latest` could destroy your application.

The images themselves are rebuild every night to keep PHP minor version, extensions and the underlying operation system up to date. So you should regularly pull your image.

**Comment by coreyworrell** [comment]
Ah okay, thanks very much for the explanation. I will give `webdevops/php-apache-dev:7.4-alpine` a try then instead.
