### ISSUE TITLE
No error message about missing web roor

### ISSUE THREAD

**Issue by fsaris** [webdevops/Dockerfile#48]
If the ``WEB_DOCUMENT_ROOT`` folder defined in ``etc/environment.ym`l` doesn't exist that Apache daemon fails silently.

Would be really helpful if there was an error message during boot up of container.

**Comment by ve3** [comment]
WEB_DOCUMENT_ROOT = /app

cd /app
-sh: cd: can't cd to /app

So, where the web root is?

**Comment by mblaschke** [comment]
In Docker images build after around March 6th the warning is included.

Which image do you use?

**Comment by ve3** [comment]
https://hub.docker.com/r/webdevops/php-apache/

webdevops/php-apache:ubuntu-12.04

I can't go to web root folder because don't know where it is.

"/opt/docker" is not exists.  
I can't change config of anything because "/opt/docker" is not exists which means "/opt/docker/etc/httpd/php.conf" is not exists too.

**Comment by mblaschke** [comment]
can you show me the output of `docker images |grep php-apache`?

**Comment by ve3** [comment]
webdevops/php-apache   latest              9634c3a25251        40 hours ago        824.3 MB

**Comment by mblaschke** [comment]
Hm.. you only have the latest image (which is ubuntu-14.04).

I've downloaded the latest ubuntu-12.04 image and `/opt/docker` is available:
![image](https://cloud.githubusercontent.com/assets/7583579/14748450/05028f82-08ba-11e6-8083-bc49d54dbec1.png)

**Comment by ve3** [comment]
I install using this command.
`docker run webdevops/php-apache:ubuntu-12.04` why it becomes ubuntu 14.04?

when i try to ssh into docker and run php -v i got php 5.3 installed. it seems to installed correctly. but no folders.

**Comment by mblaschke** [comment]
Are you sure that you've ssh'd into the correct box? Please execute `docker run -ti --rm webdevops/php-apache:ubuntu-12.04 ls -l /opt/docker`

SSH is not active by default in our images so make sure that you not ssh'd to docker host (the host is just the server which runs the docker host, not the container which you are running).

**Comment by ve3** [comment]
I have only one image/container that is this ubuntu12.04 with php5.3.
I have nothing else in docker because i'm new here and just trying to test how these work but no luck.
I removed all images/containers (which i have only one) and try to run again but now it stuck at ...

> .........
> _ssl/2.2.22 OpenSSL/1.0.1 configured -- resuming normal operations
> 2016-04-22 16:59:04,931 INFO success: syslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2016-04-22 16:59:04,932 INFO success: syslog-log entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by mblaschke** [comment]
If you're using `docker run webdevops/php-apache:ubuntu-12.04` only `supervisord` starts and starts all parent services (eg. apache, php-fpm, syslog-ng...). That's normal.

The docker image is only one part for your developing processes. Try using PHP Docker Boilerplate because it's an example for using docker with automatically sharing your files into Docker.

Docker don't care about your files, you have to upload or to mount them to get them inside.
But you're already running the container :)

If you want to jump into a container (and don't want any services to be started) you can use:
`docker run -ti --rm webdevops/php-apache:ubuntu-12.04 bash`
